### PR TITLE
Rename step types to simplify some more

### PR DESCRIPTION
**Pull request by martinthomson**
This touches a bunch of code, but it is an automated rename so you can repeat it on your branch to rebase (then use `git merge -s ours rename-step` to create a commit that integrates this change).

### CODE REVIEW

**Comment by martinthomson** [comment]
Note that this requires rebase, but it is easier to just redo this.  Renames are mechanical.  Review with that in mind.

Change is
* UniqueStepId -> Step (this is what most people will be dealing with
* Step -> SubStep (you might be minting these, but they won't appear in the algorithms anywhere)

**Review by benjaminsavage — APPROVED** [review]
Sure, why not =)

**Review by akoshelev — APPROVED** [review]

**Comment by martinthomson** [comment]
Clippy doesn't like this.  I'll need to take another look later.

**Comment by benjaminsavage** [comment]
Do we still want to do this? Or should we just abandon this diff?

**Comment by martinthomson** [comment]
I abandoned it, but made the change manually instead.  These rename changes are a nuisance.

**Pull request closed without merging**
