### PR TITLE
Remove cpu=native flag from release checks

### PR DESCRIPTION
**Pull request by akoshelev**
We started getting compile errors from `curve25519-dalek` recently: https://github.com/private-attribution/ipa/actions/runs/6769658075/job/18396480025?pr=834

would be great to know the root cause, but nothing has been reported in their repo.

### CODE REVIEW

**Comment by andyleiserson** [comment]
Maybe the github actions executors are not all the same type of machine?

**Review by andyleiserson — APPROVED** [review]

**Comment by akoshelev** [comment]
> Maybe the github actions executors are not all the same type of machine?

yep, that's certainly true because these actions can succeed if retried enough times. It still feels that it shouldn't be happening but there are other things on our plate right now :(

**Comment by akoshelev** [comment]
Failed run

https://github.com/private-attribution/ipa/actions/runs/6774614181/job/18412075070

```
Current runner version: '2.311.0'
Operating System
  Ubuntu
  22.04.3
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20231030.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231030.2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231030.2
Runner Image Provisioner
  2.0.312.1
```


Successful run:
https://github.com/private-attribution/ipa/actions/runs/6774614181/job/18413983861

```
Current runner version: '2.311.0'
Operating System
  Ubuntu
  22.04.3
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20231030.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231030.2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231030.2
Runner Image Provisioner
  2.0.312.1
```

**Comment by akoshelev** [comment]
Looks like everything works now, I am going to hold off from pushing it for now

**Pull request closed without merging**
