### PR TITLE
Pass out `Arc<Prss>` instead of `&Prss`

### PR DESCRIPTION
**Pull request by martinthomson**
This avoids using unsafe code, but I'm not sure if it is better as it adds a bunch of overhead.  I'm going to run some tests to see if this has any real effect in practice.

### CODE REVIEW

**Review by akoshelev — APPROVED** [review]
would definitely be interesting to compare these two implementations

**Comment by martinthomson** [comment]
I'm getting so much noise in testing that I can't tell if my original patch is altering performance characteristics.  That leaves me at a loss to determine what this one does.  My ancient CPU clearly doesn't like this code very much.

**Comment by akoshelev** [comment]
> I'm getting so much noise in testing that I can't tell if my original patch is altering performance characteristics. That leaves me at a loss to determine what this one does. My ancient CPU clearly doesn't like this code very much.

Let me do this - we have 3 AWS hosts that we can use to benchmark

**Comment by akoshelev** [comment]
I am getting an error trying to compile this branch - looks like it is not fully ready to be merged

```bash
error[E0277]: the trait bound `std::string::String: protocol::Step` is not satisfied
  --> src/test_fixture/circuit.rs:42:49
   |
42 |         let bit_ctx = narrow_contexts(&top_ctx, &format!("bit{}", bit));
   |                       ---------------           ^^^^^^^^^^^^^^^^^^^^^^ the trait `protocol::Step` is not implemented for `std::string::String`
   |                       |
   |                       required by a bound introduced by this call
   |
   = help: the following other types implement trait `protocol::Step`:
             IpaProtocolStep
             ShuffleStep
             SortStep
             StreamingStep
note: required by a bound in `narrow_contexts`
  --> src/test_fixture/mod.rs:45:17
   |
43 | pub fn narrow_contexts<'a>(
   |        --------------- required by a bound in this
44 |     contexts: &[ProtocolContext<'a, Arc<InMemoryEndpoint>>; 3],
45 |     step: &impl Step,
   |                 ^^^^ required by this bound in `narrow_contexts`
```

**Comment by martinthomson** [comment]
Right.  I just need to rebase onto main.  Which is on my TODO list.  The hack I have for the circuit is in place.

**Comment by martinthomson** [comment]
Lumping this in with the other one now to save on conflict management (this was already a bad merge and I had to do another hard merge on #127).

**Comment by akoshelev** [comment]
after #128 is merged I can run the benchmarks again. For some reason criterion wasn't showing me the diff between two runs :(

**Pull request closed without merging**
