### PR TITLE
Kill the Arc inside Context::Inner

### PR DESCRIPTION
**Pull request by akoshelev**
Turns out we don't need it

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]
Any indication that this saves cycles?

**Comment by martinthomson** [comment]
Note the error on the coverage build:

```
  = note: /usr/bin/ld: final link failed: No space left on device
```

**Comment by akoshelev** [comment]
> Any indication that this saves cycles?

I'd love to test that, but #921 is a blocker for it. @richajaindce have you had a chance to take a look and see what is broken inside the compact gate script generator?

**Comment by richajaindce** [comment]
> > Any indication that this saves cycles?
> 
> I'd love to test that, but #921 is a blocker for it. @richajaindce have you had a chance to take a look and see what is broken inside the compact gate script generator?

I checked the history of steps.txt and it supported upto depth 31 meaning 2^31! This was then overwritten by OPRF changes. Not sure how we generated so many steps but working to find a way to get them in again

**Pull request merged**
