### PR TITLE
DP parameters

### PR DESCRIPTION
**Pull request by martinthomson**
This is a sketch of how things might work for configuring DP.  Needs rebasing.

### CODE REVIEW

**Comment by andyleiserson** [comment]
Maybe this is bikeshed territory, but does it make sense to have a more generic way to specify a privacy mechanism and its parameters? I'm thinking something like `privacy: Option<PrivacyMechanism>` where `PrivacyMechanism` is an enum, instead of `dp: Option<DifferentialPrivacy>`. I feel like we may pretty quickly want to add other options here (e.g. different noise distributions, randomized response, or even simple variants like a specified epsilon combined with an implicit delta, or a way to say "spend x% of my privacy budget for this query").

(I don't totally like my `privacy: Option<PrivacyMechanism>` suggestion because it results in the rather unfortunate `privacy: None`. But I'm not immediately sure how to do better without making it too verbose.)

**Comment by martinthomson** [comment]
I think that you mean `privacy: PrivacyMechanism`.  Then we can do something like:

```rust
enum PrivacyMechanism {
  DifferentialPrivacy(DifferentialPrivacy),
  #[cfg(feature = "no-privacy")]
  None,
}
```

**Comment by benjaminsavage** [comment]
Can we close this PR?

**Comment by martinthomson** [comment]
Yeah, I think we'll need to come back to this, but it's not worth rebasing this now.

**Pull request closed without merging**
